# arguments for dataset
dataset: scgm
data_root: /data/qmy/Dataset
n_domains: 4
n_channels: 1
n_classes: 2
image_size: 288
unlabel_validation: true # whether unlabeled data has labels for validation

# arguments for training
epochs: 50
iters: 200
batch_size: 12
